### ISSUE TITLE
已关闭

### ISSUE THREAD

**Issue by 1759749908** [EssayKillerBrain/EssayKiller_V2#3]
![微信图片_20201002100212](https://user-images.githubusercontent.com/28804414/94881033-4b9bb300-0497-11eb-8a89-8000705d9e89.png)
![xjp](https://user-images.githubusercontent.com/28804414/94881068-56eede80-0497-11eb-9c46-564f3de2ae11.png)

**Comment by db005** [comment]
要了命了。

**Comment by shayxu-ai** [comment]
最后再接个不良文字屏蔽系统。感觉有点意思

**Comment by fuhaixiao** [comment]
@1759749908 他执政了55年吗?我的天

**Comment by HuangChangHuai** [comment]
必须封！墙了github

**Comment by Destroyer-LDB** [comment]
……封了！这话可不敢乱说!

**Comment by xiaoland** [comment]
害怕😱，这是从未来来的稿子吗

**Comment by shianlin2084** [comment]
嫉妒让你面目全非
