### ISSUE TITLE
colab网页版卡在第二部分中perl指令处，持续下载

### ISSUE THREAD

**Issue by 112292454** [EssayKillerBrain/EssayKiller_V2#35]
网页版挂着十几个小时直到连接自动断开也没有下载完毕，期间这几行重复出现，只是resolving和connecting两行的ip地址，和下载速度在改变；右上角ram占用极低

`
--2022-06-07 12:12:38--  https://docs.google.com/uc?id=1A910UqSNBBi_SEoIDl15095T_5kojESO&export=download
Resolving docs.google.com (docs.google.com)... 74.125.31.113, 74.125.31.102, 74.125.31.101, ...
Connecting to docs.google.com (docs.google.com)|74.125.31.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘trained_models/model.ckpt-280000.data-00000-of-00001’

     0K                                     13.5M=0s

2022-06-07 12:12:38 (13.5 MB/s) - ‘trained_models/model.ckpt-280000.data-00000-of-00001’ saved [2241]
`

`
--2022-06-07 12:12:38--  https://docs.google.com/uc?id=1A910UqSNBBi_SEoIDl15095T_5kojESO&export=download
Resolving docs.google.com (docs.google.com)... 173.194.218.138, 173.194.218.139, 173.194.218.113, ...
Connecting to docs.google.com (docs.google.com)|173.194.218.138|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘trained_models/model.ckpt-280000.data-00000-of-00001’

     0K                                     29.5M=0s
2022-06-07 12:12:38 (29.5 MB/s) - ‘trained_models/model.ckpt-280000.data-00000-of-00001’ saved [2241]
`

**Comment by trustyboy** [comment]
EssayKiller_V2/blob/master/LanguageNetwork/GPT2/scripts/gdown.pl 里面改下：
`if ($URL=~m#^https?://drive.google.com/file/d/([^/]+)#) {
    $URL="https://docs.google.com/uc?id=$1&export=download&confirm=t";
}
elsif ($URL=~m#^https?://drive.google.com/open\?id=([^/]+)#) {
    $URL="https://docs.google.com/uc?id=$1&export=download&confirm=t";
}
`

**Comment by 112292454** [comment]
试了一下  训练的文本是不是加入了什么奇怪的东西hhhh，感觉有点像从网上爬到的文章
就是直接复制的去年高考的作文题目，输出很奇怪

“同样，你现在也在知乎上回答这个问题，本身就是符合你的初心的。”
”以下截图是一个愚蠢者的表述，仅供大家参考，多看多体会，共勉！沪北薯条哲学研究简介您来人间一趟。“
“贴出来的，更深刻的理由是目前其中回答能被各大高校利用的有限资源还不够请您参考这个问题的各种答案。”
”当然自己也在思考，我们需要不断努力的赚钱，让自己变得美丽精致。去年痛恨摇滚乐，但是自己并不喜欢摇滚乐，喜欢的是搞个摇滚乐的演唱者。现在，转角处，有人向我，不孝有三，无后为大，十个人在共产主义圣召里，我不敢在身边。“
